# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('collaborator1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_c1', to=settings.AUTH_USER_MODEL)),
                ('collaborator2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_c2', to=settings.AUTH_USER_MODEL)),
                ('collaborator3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_c3', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
